<?php
$sesstart="on";
echo"
        <div style='height:20px;'></div>
        <div>
                <a href='#' onclick=post('page/page_staff_add_form','','proses')><img src='images/newfile.jpg' height=40px border=0 title='Create New Document'></a>
		<a href='#' onclick=post('page/page_staff_add_form','".md5("v")."=".md5("p")."&nik='+document.form1.nik.value+'&nama='+document.form1.nama.value+'&gelar='+document.form1.gelar.value+'&tempatlahir='+document.form1.tempatlahir.value+'&tanggallahir='+document.form1.tanggallahir.value+'&bulanlahir='+document.form1.bulanlahir.value+'&tahunlahir='+document.form1.tahunlahir.value+'&jeniskelamin='+document.form1.jeniskelamin.value+'&warganegara='+document.form1.warganegara.value+'&agama='+document.form1.agama.value+'&alamat='+document.form1.alamat.value+'&kecamatan='+document.form1.kecamatan.value+'&kota='+document.form1.kota.value+'&provinsi='+document.form1.provinsi.value+'&telprumah='+document.form1.telprumah.value+'&telphp='+document.form1.telphp.value+'&luluspend='+document.form1.luluspend.value+'&sekolah='+document.form1.sekolah.value+'&noijasah='+document.form1.noijasah.value+'&statusnikah='+document.form1.statusnikah.value+'&namasi='+document.form1.namasi.value+'&alamatsi='+document.form1.alamatsi.value+'&kecamatansi='+document.form1.kecamatansi.value+'&kotasi='+document.form1.kotasi.value+'&provinsisi='+document.form1.provinsisi.value+'&telprumahsi='+document.form1.telprumahsi.value+'&telphpsi='+document.form1.telphpsi.value+'&jobsi='+document.form1.jobsi.value+'&tanggalmasuk='+document.form1.tanggalmasuk.value+'&bulanmasuk='+document.form1.bulanmasuk.value+'&tahunmasuk='+document.form1.tahunmasuk.value+'&lamakontrak='+document.form1.lamakontrak.value+'&jobstatus='+document.form1.jobstatus.value+'&jobbagian='+document.form1.jobbagian.value+'&jobbagianketerangan='+document.form1.jobbagianketerangan.value+'&jobsubbagian='+document.form1.jobsubbagian.value+'&jobline='+document.form1.jobline.value+'&jobgajiharian='+document.form1.jobgajiharian.value+'&jobstatuskontrak='+document.form1.jobstatuskontrak.value,'proses')><img src='images/save.jpg' height=40px border=0 title='Save Document'></a>
		<a href='#' onclick=post('page/page_staff_add_form','".md5("v")."=".md5("s")."','proses')><img src='images/search.jpg' height=40px border=0 title='Search Document'></a>
		<a href='#' onclick=document.form1.nik.value='';document.form1.nama.value='';document.form1.gelar.value='';document.form1.tempatlahir.value='';document.form1.tanggallahir.value='';document.form1.bulanlahir.value='';document.form1.tahunlahir.value='';document.form1.jeniskelamin.value='';document.form1.warganegara.value='';document.form1.agama.value='';document.form1.alamat.value='';document.form1.kecamatan.value='';document.form1.kota.value='';document.form1.provinsi.value='';document.form1.telprumah.value='';document.form1.telphp.value='';document.form1.luluspend.value='';document.form1.sekolah.value='';document.form1.noijasah.value='';document.form1.statusnikah.value='';document.form1.namasi.value='';document.form1.alamatsi.value='';document.form1.kecamatansi.value='';document.form1.kotasi.value='';document.form1.provinsisi.value='';document.form1.telprumahsi.value='';document.form1.telphpsi.value='';document.form1.jobsi.value='';document.form1.tanggalmasuk.value='';document.form1.bulanmasuk.value='';document.form1.tahunmasuk.value='';document.form1.lamakontrak.value='';document.form1.jobstatus.value='';document.form1.jobbagian.value='';document.form1.jobbagianketerangan.value='';document.form1.jobsubbagian.value='';document.form1.jobline.value='';document.form1.jobgajiharian.value='';document.form1.jobstatuskontrak.value='';><img src='images/delete.jpg' height=40px border=0 title='Clear Formulir'></a>
	</div>
	<div id='proses'>";
include("page_staff_add_form.php");
echo"
	</div>
";
?>
