<?PHP
define("PROJECT_NAME", 'OlaBasket');
define("PROJECT_VERSION", '1.0');
define("RUPEE_SIGN", '₹');
define("TODAY_DATE", date("Y-m-d"));
define("UPLOAD", 'upload/');
define("CATEGORY_IMAGE_FOLDER", 'category/');
define("TEAM_IMAGE_FOLDER", 'team/');
define("EVENT_IMAGE_FOLDER", 'event/');
define("GALLERY_IMAGE_FOLDER", 'gallery/');
define("PRODUCT_IMAGE_FOLDER", 'product/');
define("USER", 'user_master');
define("CATEGORY", 'category_master');
define("GALLERY", 'gallery_master');
define("TEAM", 'team_master');
define("PRODUCT", 'product_master');
define("CONTACT_INQUIRY", 'contact_inquiry_master');
define("LABEL", 'label_master');
define("SEO", 'seo_master');
define("EVENT", 'event_master');
define("LOGIN_SUCCESS", 'Great !!! You Are Logged Successfully.');
define("REGISTER_SUCCESS", 'Great !!! You Are Registered Successfully.');
define("SOMETHING_WENT_WRONG", 'Opps !!! Something Went Wrong.');
define("ENTER_VALID_DETAILS", 'Please Enter Valid Details.');
define("RECORD_DELETED", 'Great !!! Record Deleted.');
define("RECORD_NOT_DELETED", 'Opps !!! Record Not Deleted.');
define("RECORD_FOUND", 'Great !!! Record Found.');
define("RECORD_NOT_FOUND", 'Opps !!! Record Not Found.');
define("RECORD_UPDATED", 'Great !!! Record Updated.');
define("RECORD_NOT_UPDATED", 'Opps !!! Record Not Updated.');
define("RECORD_INSERTED", 'Great !!! Record Inserted.');
define("RECORD_NOT_INSERTED", 'Opps !!! Record Not Inserted.');
define("SCS", "true");
define("FAIL", "false");
?>